download:
	git clone https://github.com/lexibank/allenbai; cd allenbai; git checkout v4.0
	git clone https://github.com/intercontinental-dictionary-series/idssegmented; cd idssegmented; git checkout v2.0
colexifications:
	python compute-graphs.py
computation-time:
	python computing-time-comparison.py
compare-graphs:
	python compare-graphs.py
subgraphs:
	python extract-subgraphs.py
